### ISSUE TITLE
Session.setAuth not auto deleting after logout

### ISSUE THREAD

**Issue by aadamsx** [okgrow/meteor-persistent-session#9]
I can set a session with Session.setAuth(key, value), then log out, and log back in and the value is still there.  I'm using account-ui-bootstrap-3 (just a wrapper on account-ui) and account-password at the moment.

After I log out and then back in, I can still see the value in LocalStorage.

**Comment by rgould** [comment]
@aadamsx @mvaivre Sorry for the delay. I can't seem to replicate this at all :crying_cat_face: 

Are you still experiencing this problem? If so, are you able to reliably replicate it (and include steps here or point to a test app)? If so, reopen this issue when you comment.

**Comment by afoda** [comment]
I have also experienced this problem, the cause was out of order packages in `.meteor/packages`.

`u2622:persistent-session` assumes that `Meteor.logout` is already defined when it is loaded. Therefore `u2622:persistent-session` must appear *after* whichever `accounts-*` package is loading `accounts-base`, otherwise `Meteor.logout` is not overridden and `Session.clearAuth` doesn't get called on logout.

**Comment by rgould** [comment]
@afoda Thanks! This should give me enough information to fix it.
